---
apiVersion: v1
kind: Service
metadata:
  name: helm-chart-demo
  namespace: default
  labels:
    app: helm-chart-demo
spec:
  selector:
    app: helm-chart-demo
  # type: LoadBalancer
  # ports:
  # - name: http
  #   port: 8079
  #   protocol: TCP # optional protocol

  type: NodePort
  ports:
  - name: http
    port: 8082
    nodePort: 30082
    protocol: TCP # optional protocol